import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header";
import Footer from "@/components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="cupcake">
      <body className={`${inter.className} flex flex-col gap-10`}>
        <Header />
        <div className="w-screen flex justify-center">
          <div className="w-[1216px]">{children}</div>
        </div>
        <Footer />
      </body>
    </html>
  );
}
